### ISSUE TITLE
Kafka restart can be improved

### ISSUE THREAD

**Issue by v-stepanov** [zalando-incubator/bubuku#35]
Currently kafka restart is not very safe IMHO. With buku we had a situation that kafka did a start before the old one finished shutdown. We also do what buku does:
process.terminate()
process.wait()
So that doesn't guarantee that old kafka stopped. 
I know that here we additionally check that node doesn't exist in ZK any more.
But I think to be on the safe side we can also check that Java process has ended (in a hacky way)

**Comment by CyberDem0n** [comment]
My two cents on this topic:
`process.terminate()` and `process.wait()` didn't worked properly in a buku, because they were called NOT from the original process, but from the forked one. Process can watch (wait) for children, but not siblings.

**Comment by antban** [comment]
@CyberDem0n bubuku repo is gaining popularity :) I think maybe we don't need to rename it back to buku?

**Comment by CyberDem0n** [comment]
@antban somehow I was automatically subscribed to bubuku notifications, so it's not really a popularity :)

And about renaming it back... don't think it is necessary, there is not much original code left

**Comment by CyberDem0n** [comment]
By the way, you should think about using the same approach as https://github.com/zalando/planb-cassandra

They are not using ASG, but just EC2 instances with termination protection. The biggest advantage of such approach - it does not destroy EBS volumes when EC2 instance dies. And when the new instance is coming up it will attach and mount EBS with all data.

**Comment by antban** [comment]
As a result - there is nothing to discuss here...
