### ISSUE TITLE
Optimize rebalance

### ISSUE THREAD

**Issue by antban** [zalando-incubator/bubuku#36]
Right now rebalance is made step by step with step size of 1 partition.
Maybe it will be better to transfer more partitions at a time (5, 10, or by leader count), and it will be faster.

**Comment by CyberDem0n** [comment]
Doesn't really make sense, kafka does rebalance step-by-step anyway. It process one partition and updates znode. When there is nothing left - removes it.

**Comment by antban** [comment]
@CyberDem0n In some situations it may help. For example - bubuku have minimum step time - 0.5 seconds. That means, that if partition migration takes less time, than it's better to migrate several partitions at a time.

**Comment by antban** [comment]
Well, renamed task. There are problems with rebalance, and they should be fixed:
1. Rebalance should do as less steps as it's possible (do not move data that should not be moved)
2. Leaders should be balanced having in mind that there must be different leaders for partitions in single topic.
3. During fatboyslim only replicas should be moved. Leaders should remain in the same position

**Comment by antban** [comment]
Closed in favor of #63
