### ISSUE TITLE
Refresh exhibitor list in more reliable way

### ISSUE THREAD

**Issue by antban** [zalando-incubator/bubuku#37]
Now if exhibitor list can't be refreshed, than AWSExhibitorAddressProvider will query data from master_exhibitors. But it's much better to query data from AWS to get new exhibitor list from lb name.

And of course it's better not to start kafka instances if there are no exhibitor instances. 
Maybe it's better not to start kafka if exhibitor list is empty.

**Comment by rcillo** [comment]
Why is this a good idea? I thought that one of the goals of exhibitor was to discover other zookeepers and coordinate them. I thought that it would be a reliable source of information.

**Comment by antban** [comment]
@rcillo In this issue I am trying to reference exactly one situation: all the exhibitors are suddenly disappeared.
It means, that during normal work we are using zookeeper list provided by exhibitor API. But in case of catastrophic disaster (no exhibitor instances available) we need to use aws api to refresh exhibitor list, instead of trying to connect to outdated instances.
