### ISSUE TITLE
Improve the rebalace: old nodes should only give away partitions, not obtain new ones

### ISSUE THREAD

**Issue by v-stepanov** [zalando-incubator/bubuku#63]
When the new node is added to cluster and rebalance starts the old nodes sometimes get new partitions. In my understanding the rebalance should happen in a way that partitions are only moved from old nodes to the new one (in other case it can result in that old nodes can run out of disk space)

**Comment by antban** [comment]
Will copy additional information form #36 
1. Rebalance should do as less steps as it's possible (do not move data that should not be moved)
2. Leaders should be balanced having in mind that there must be different leaders for partitions in single topic.
3. During fatboyslim only replicas should be moved. Leaders should remain in the same position
