### ISSUE TITLE
Exception when trying to call `migrate`

### ISSUE THREAD

**Issue by prayerslayer** [zalando-incubator/bubuku#71]
Hi,

we have a Kafka cluster and I want to move partitions to other nodes. As far as I understand, this is what `bubuku-cli migrate` is for.

However when I call it like this:

~~~
$ bubuku-cli stats
Broker Id  Free kb     Used kb  
52397540   464380884   42792420 
52399021   4930335540  26419188 
52400677   4801094116  155660612
52402004   478177812   28995492 
52404200   486099964   21073340
~~~

    $ bubuku-cli migrate --from "52399021,52400677" --to "52402004,52404200,52397540"

I get the following error:

~~~
INFO:kazoo.client:Zookeeper session lost, state: CLOSED
Traceback (most recent call last):
  File "/usr/local/bin/bubuku-cli", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/bubuku/cli.py", line 94, in migrate_broker
    RemoteCommandExecutorCheck.register_migration(zookeeper, from_.split(','), to.split(','), shrink, broker_id)
AttributeError: 'NoneType' object has no attribute 'split'
~~~

Seems like either `from` or `to` is not picked up correctly by `click`? Should I use a different format?

Thanks!

**Comment by antban** [comment]
@prayerslayer Well, initially this feature was developed to migrate to other nodes (direct transfer). Imagine that you have nodes A, B, C. You want to replace nodes A and B with D and E (one to one only). 
Then you have to call `--from "A,B" -- to "D,E"`.
Logging message should be improved anyway, as well as documentation

**Comment by prayerslayer** [comment]
I see, but wouldn't that be a different error? The message suggests that `split` is called on `None`.

**Comment by prayerslayer** [comment]
Ping :)

**Comment by antban** [comment]
@prayerslayer Now I see wat you mean, I'll take a closer look to it

**Comment by antban** [comment]
@prayerslayer Yes, it doesn't work now for some reason and should be fixed
